.\" This file is part of the uCodev Bandwidth Tester (ubwt) project (https://www.ucodev.org)
.TH UBWT "8" "April 2021" "uCodev Bandwidth Tester" "User Commands"
.SH NAME
ubwt \- uCodev Bandwidth Tester
.SH SYNOPSIS
.B ubwt
[ \fIOPTIONS\fR ] { \fIconnector\fR | \fIlistener\fR } { \fIHOSTNAME\fR | \fIIPv4\fR | \fIIPv6\fR }
.SH DESCRIPTION
.PP
The \fBubwt\fR(8) (uCodev Bandwidth Tester) is a command line binary utility designed to perform network bandwidth testing. It allows unidirectional (\fBdefault\fR), bidirectional (\fB\-b\fR), reverse (\fB\-R\fR) and asynchronous full-duplex (\fB\-A\fR) testing modes, providing a summary of the network bandwidth capabilities, or an extended report (\fB\-F\fR).
.PP
It consists of a single binary tool that can act as a \fBconnector\fR in one end, and as a \fBlistener\fR on another end, allowing multiple concurrent connections by using multiple workers (\fB\-W\fR), each worker representing one connection.
.PP
The addresses of the listener and connector can be specified as a \fBHOSTNAME\fR, an \fBIPv4\fR or as an \fBIPv6\fR.
.PP
.SH OPTIONS
When using command line \fBOPTIONS\fR with \fBubwt\fR(8), make sure they are exactly the same on both listener and connector. Failing to do so, one of the ends will either reject the other end transmission, or the behaviour of one or both ends will be undefined.
.PP
The available command line \fBOPTIONS\fR are:
.PP
.TP
\fB\-A\fR
Asynchronous bi-directional full-duplex test. TCP only.
.TP
\fB\-d\fR \fIFILE\fR
Append debugging output to a file (default: stderr).
.TP
\fB\-D\fR
Enable debugging.
.TP
\fB\-b\fR
Perform a bi-directional test.
.TP
\fB\-F\fR
Enable full/extended reporting.
.TP
\fB\-h\fR
Prints the help.
.TP
\fB\-I\fR \fIMSEC\fR
Interval between latency measurements (default: 1 msec).
.TP
\fB\-j\fR \fIFILE\fR
Export report in JSON format to file.
.TP
\fB\-m\fR \fIOCTETS\fR
Link MTU (default: 1500 octets).
.TP
\fB\-M\fR \fIMULTIPLIER\fR
Talk count multiplier (default: auto).
.TP
\fB\-N\fR \fIITERATIONS\fR
Number of handshake iterations (default: 20 iterations).
.TP
\fB\-o\fR \fISECONDS\fR
Process reverse delay. Sets -b (default: 3 seconds).
.TP
\fB\-O\fR \fISECONDS\fR
Maximum wait time before next stream (default: 20 seconds).
.TP
\fB\-p\fR \fIPROTOCOL\fR
L4 protocol: 'tcp' or 'udp' (default: tcp).
.TP
\fB\-P\fR \fIPORT\fR
TCP or UDP port to listen/connect to (default: 19991).
.TP
\fB\-r\fR \fIFILE\fR
Store the running PID into the specified file.
.TP
\fB\-R\fR
Reverse stream testing first.
.TP
\fB\-s\fR \fIOCTETS\fR
L4 payload size (default: 1432).
.TP
\fB\-t\fR \fISECONDS\fR
Minimum stream time (default: 3 seconds).
.TP
\fB\-T\fR \fISECONDS\fR
Maximum wait time between stream packets (default: 5 seconds).
.TP
\fB\-v\fR
Display version information.
.TP
\fB\-w\fR \fISECONDS\fR
Connection timeout (default: 120 seconds).
.TP
\fB\-W\fR \fICOUNT\fR
Maximum number of workers (default: 1). TCP only.
.SH EXAMPLE
.TP
alice@serv.my.lan ~ $ ubwt listener 0.0.0.0
.TP
bob@client.my.lan ~ $ ubwt connector serv.my.lan
.SH AUTHOR
Written by Pedro A. Hortas (pah@ucodev.org).
.SH "REPORTING BUGS"
Report ubwt bugs to \fIpah@ucodev.org\fR
.SH COPYRIGHT
.PP
Copyright \(co 2021  Pedro A. Hortas (pah@ucodev.org)
.PP
License: GNU GPL version 3 or later <http://gplv3.fsf.org/>
.PP
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.PP
